// Date: 7/30/2016 9:16:45 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class BeastModel extends ModelBase {
	// fields
	ModelRenderer Leg2;
	ModelRenderer Leg;
	ModelRenderer Body;
	ModelRenderer Arm2;
	ModelRenderer Arm;
	ModelRenderer Shape1;

	public BeastModel() {
		textureWidth = 128;
		textureHeight = 50;

		Leg2 = new ModelRenderer(this, 0, 0);
		Leg2.addBox(0F, 0F, 0F, 4, 8, 4);
		Leg2.setRotationPoint(4F, 16F, 0F);
		Leg2.setTextureSize(128, 50);
		Leg2.mirror = true;
		setRotation(Leg2, 0F, 0F, 0F);
		Leg = new ModelRenderer(this, 0, 0);
		Leg.addBox(0F, 0F, 0F, 4, 8, 4);
		Leg.setRotationPoint(-8F, 16F, 0F);
		Leg.setTextureSize(128, 50);
		Leg.mirror = true;
		setRotation(Leg, 0F, 0F, 0F);
		Body = new ModelRenderer(this, 62, 24);
		Body.addBox(0F, 0F, 0F, 16, 18, 8);
		Body.setRotationPoint(-8F, -2F, -2F);
		Body.setTextureSize(128, 50);
		Body.mirror = true;
		setRotation(Body, 0F, 0F, 0F);
		Arm2 = new ModelRenderer(this, 34, 0);
		Arm2.addBox(0F, 0F, 0F, 3, 12, 3);
		Arm2.setRotationPoint(-11F, -1F, 0F);
		Arm2.setTextureSize(128, 50);
		Arm2.mirror = true;
		setRotation(Arm2, 0F, 0F, 0F);
		Arm = new ModelRenderer(this, 34, 0);
		Arm.addBox(0F, 0F, 0F, 3, 12, 3);
		Arm.setRotationPoint(8F, -1F, 0F);
		Arm.setTextureSize(128, 50);
		Arm.mirror = true;
		setRotation(Arm, 0F, 0F, 0F);
		Shape1 = new ModelRenderer(this, 0, 30);
		Shape1.addBox(0F, 0F, 0F, 6, 6, 8);
		Shape1.setRotationPoint(-3F, -8F, -5F);
		Shape1.setTextureSize(128, 50);
		Shape1.mirror = true;
		setRotation(Shape1, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3,
			float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		Leg2.render(f5);
		Leg.render(f5);
		Body.render(f5);
		Arm2.render(f5);
		Arm.render(f5);
		Shape1.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3,
			float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);

		this.Shape1.rotateAngleY = f3 / (180F / (float) Math.PI);
		this.Shape1.rotateAngleX = f4 / (180F / (float) Math.PI);
		this.Arm.rotateAngleX = MathHelper.cos(f * 0.6662F + (float) Math.PI)
				* 2.0F * f1 * 0.5F;
		this.Arm2.rotateAngleX = MathHelper.cos(f * 0.6662F) * 2.0F * f1 * 0.5F;
		this.Arm.rotateAngleZ = 0.0F;
		this.Arm2.rotateAngleZ = 0.0F;
		this.Leg.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
		this.Leg2.rotateAngleX = MathHelper.cos(f * 0.6662F + (float) Math.PI)
				* 1.4F * f1;
		this.Leg.rotateAngleY = 0.0F;
		this.Leg2.rotateAngleY = 0.0F;

	}

}
