// Date: 6/26/2016 8:20:53 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class CreepPig extends ModelBase {
	// fields
	ModelRenderer body;
	ModelRenderer leg1;
	ModelRenderer leg2;
	ModelRenderer leg3;
	ModelRenderer leg4;
	ModelRenderer Neck;
	ModelRenderer Head;

	public CreepPig() {
		textureWidth = 100;
		textureHeight = 128;

		body = new ModelRenderer(this, 28, 23);
		body.addBox(-5F, -10F, -7F, 10, 16, 8);
		body.setRotationPoint(0F, 11F, 3F);
		body.setTextureSize(100, 128);
		body.mirror = true;
		setRotation(body, 1.570796F, 0F, 0F);
		leg1 = new ModelRenderer(this, 11, 0);
		leg1.addBox(-2F, 0F, -2F, 4, 6, 4);
		leg1.setRotationPoint(-3F, 18F, 7F);
		leg1.setTextureSize(100, 128);
		leg1.mirror = true;
		setRotation(leg1, 0F, 0F, 0F);
		leg2 = new ModelRenderer(this, 11, 0);
		leg2.addBox(-2F, 0F, -2F, 4, 6, 4);
		leg2.setRotationPoint(3F, 18F, 7F);
		leg2.setTextureSize(100, 128);
		leg2.mirror = true;
		setRotation(leg2, 0F, 0F, 0F);
		leg3 = new ModelRenderer(this, 11, 0);
		leg3.addBox(-2F, 18F, -2F, 4, 6, 4);
		leg3.setRotationPoint(-3F, 0F, -5F);
		leg3.setTextureSize(100, 128);
		leg3.mirror = true;
		setRotation(leg3, 0F, 0F, 0F);
		leg4 = new ModelRenderer(this, 11, 0);
		leg4.addBox(-2F, 0F, -2F, 4, 6, 4);
		leg4.setRotationPoint(3F, 18F, -5F);
		leg4.setTextureSize(100, 128);
		leg4.mirror = true;
		setRotation(leg4, 0F, 0F, 0F);
		Neck = new ModelRenderer(this, 0, 61);
		Neck.addBox(0F, 0F, 0F, 10, 10, 6);
		Neck.setRotationPoint(-5F, 3F, -11F);
		Neck.setTextureSize(100, 128);
		Neck.mirror = true;
		setRotation(Neck, 0.2602503F, 0F, 0F);
		Head = new ModelRenderer(this, 42, 90);
		Head.addBox(0F, 0F, 0F, 7, 7, 7);
		Head.setRotationPoint(-3.5F, 0F, -15F);
		Head.setTextureSize(100, 128);
		Head.mirror = true;
		setRotation(Head, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3,
			float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		body.render(f5);
		leg1.render(f5);
		leg2.render(f5);
		leg3.render(f5);
		leg4.render(f5);
		Neck.render(f5);
		Head.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float p_78087_1_, float p_78087_2_,
			float p_78087_3_, float p_78087_4_, float p_78087_5_,
			float p_78087_6_, Entity p_78087_7_) {
		float f6 = (180F / (float) Math.PI);
		this.Head.rotateAngleX = p_78087_5_ / (180F / (float) Math.PI);
		this.Head.rotateAngleY = p_78087_4_ / (180F / (float) Math.PI);
		this.body.rotateAngleX = ((float) Math.PI / 2F);
		this.leg1.rotateAngleX = MathHelper.cos(p_78087_1_ * 0.6662F) * 1.4F
				* p_78087_2_;
		this.leg2.rotateAngleX = MathHelper.cos(p_78087_1_ * 0.6662F
				+ (float) Math.PI)
				* 1.4F * p_78087_2_;
		this.leg3.rotateAngleX = MathHelper.cos(p_78087_1_ * 0.6662F
				+ (float) Math.PI)
				* 1.4F * p_78087_2_;
		this.leg4.rotateAngleX = MathHelper.cos(p_78087_1_ * 0.6662F) * 1.4F
				* p_78087_2_;
	}

}
