// Date: 5/3/2016 9:07:25 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package model;

import org.lwjgl.opengl.GL11;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.entity.EntityLivingBase;
import net.minecraft.entity.passive.EntityWolf;
import net.minecraft.util.MathHelper;

public class GreenMob extends ModelBase {
	// fields
	ModelRenderer Body;
	ModelRenderer Tail;
	ModelRenderer Leg4;
	ModelRenderer Leg3;
	ModelRenderer Leg2;
	ModelRenderer Leg1;
	ModelRenderer Head;

	public GreenMob() {
		textureWidth = 64;
		textureHeight = 32;

		Body = new ModelRenderer(this, 0, 15);
		Body.addBox(0F, 0F, 0F, 3, 2, 8);
		Body.setRotationPoint(-1F, 21F, -6F);
		Body.setTextureSize(64, 32);
		Body.mirror = true;
		setRotation(Body, 0F, 0F, 0F);
		Tail = new ModelRenderer(this, 0, 7);
		Tail.addBox(0F, 0F, 0F, 1, 1, 4);
		Tail.setRotationPoint(0F, 21F, 2F);
		Tail.setTextureSize(64, 32);
		Tail.mirror = true;
		setRotation(Tail, 0F, 0F, 0F);
		Leg4 = new ModelRenderer(this, 0, 0);
		Leg4.addBox(0F, 0F, 0F, 1, 2, 1);
		Leg4.setRotationPoint(2F, 22F, 1F);
		Leg4.setTextureSize(64, 32);
		Leg4.mirror = true;
		setRotation(Leg4, 0F, 0F, 0F);
		Leg3 = new ModelRenderer(this, 0, 0);
		Leg3.addBox(0F, 0F, 0F, 1, 2, 1);
		Leg3.setRotationPoint(-2F, 22F, 1F);
		Leg3.setTextureSize(64, 32);
		Leg3.mirror = true;
		setRotation(Leg3, 0F, 0F, 0F);
		Leg2 = new ModelRenderer(this, 0, 0);
		Leg2.addBox(0F, 0F, 0F, 1, 2, 1);
		Leg2.setRotationPoint(-2F, 22F, -6F);
		Leg2.setTextureSize(64, 32);
		Leg2.mirror = true;
		setRotation(Leg2, 0F, 0F, 0F);
		Leg1 = new ModelRenderer(this, 0, 0);
		Leg1.addBox(0F, 0F, 0F, 1, 2, 1);
		Leg1.setRotationPoint(2F, 22F, -6F);
		Leg1.setTextureSize(64, 32);
		Leg1.mirror = true;
		setRotation(Leg1, 0F, 0F, 0F);
		Head = new ModelRenderer(this, 26, 18);
		Head.addBox(0F, 0F, 0F, 3, 3, 4);
		Head.setRotationPoint(-1F, 20F, -10F);
		Head.setTextureSize(64, 32);
		Head.mirror = true;
		setRotation(Head, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3,
			float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		Head.render(f5);
		Body.render(f5);
		Tail.render(f5);
		Leg1.render(f5);
		Leg2.render(f5);
		Leg3.render(f5);
		Leg4.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3,
			float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
