// Date: 6/5/2016 4:58:41 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class OddModel extends ModelBase {
	// fields
	ModelRenderer Leg3;
	ModelRenderer Leg2;
	ModelRenderer Leg4;
	ModelRenderer Leg1;
	ModelRenderer Shape1;
	ModelRenderer Shape2;

	public OddModel() {
		textureWidth = 64;
		textureHeight = 32;

		Leg3 = new ModelRenderer(this, 0, 14);
		Leg3.addBox(0F, 0F, 0F, 3, 15, 3);
		Leg3.setRotationPoint(-5F, 9F, 0F);
		Leg3.setTextureSize(64, 32);
		Leg3.mirror = true;
		setRotation(Leg3, 0F, 0F, 0F);
		Leg2 = new ModelRenderer(this, 0, 14);
		Leg2.addBox(0F, 0F, 0F, 3, 15, 3);
		Leg2.setRotationPoint(2F, 9F, 0F);
		Leg2.setTextureSize(64, 32);
		Leg2.mirror = true;
		setRotation(Leg2, 0F, 0F, 0F);
		Leg4 = new ModelRenderer(this, 0, 0);
		Leg4.addBox(0F, 0F, 0F, 3, 9, 3);
		Leg4.setRotationPoint(2F, 15F, 12F);
		Leg4.setTextureSize(64, 32);
		Leg4.mirror = true;
		setRotation(Leg4, 0F, 0F, 0F);
		Leg1 = new ModelRenderer(this, 0, 0);
		Leg1.addBox(0F, 0F, 0F, 3, 9, 3);
		Leg1.setRotationPoint(-5F, 15F, 12F);
		Leg1.setTextureSize(64, 32);
		Leg1.mirror = true;
		setRotation(Leg1, 0F, 0F, 0F);
		Shape1 = new ModelRenderer(this, 13, 12);
		Shape1.addBox(0F, 0F, 0F, 8, 3, 17);
		Shape1.setRotationPoint(-4F, 6F, 0F);
		Shape1.setTextureSize(64, 32);
		Shape1.mirror = true;
		setRotation(Shape1, -0.4833219F, 0F, 0F);
		Shape2 = new ModelRenderer(this, 25, 0);
		Shape2.addBox(0F, 0F, 0F, 6, 6, 6);
		Shape2.setRotationPoint(-3F, 3F, -5F);
		Shape2.setTextureSize(64, 32);
		Shape2.mirror = true;
		setRotation(Shape2, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3,
			float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		Leg3.render(f5);
		Leg2.render(f5);
		Leg4.render(f5);
		Leg1.render(f5);
		Shape1.render(f5);
		Shape2.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float p_78087_1_, float p_78087_2_,
			float p_78087_3_, float p_78087_4_, float p_78087_5_,
			float p_78087_6_, Entity p_78087_7_) {
		float f6 = (180F / (float) Math.PI);
		this.Shape2.rotateAngleX = p_78087_5_ / (180F / (float) Math.PI);
		this.Shape2.rotateAngleY = p_78087_4_ / (180F / (float) Math.PI);
		this.Leg1.rotateAngleX = MathHelper.cos(p_78087_1_ * 0.6662F) * 1.4F
				* p_78087_2_;
		this.Leg2.rotateAngleX = MathHelper.cos(p_78087_1_ * 0.6662F
				+ (float) Math.PI)
				* 1.4F * p_78087_2_;
		this.Leg3.rotateAngleX = MathHelper.cos(p_78087_1_ * 0.6662F
				+ (float) Math.PI)
				* 1.4F * p_78087_2_;
		this.Leg4.rotateAngleX = MathHelper.cos(p_78087_1_ * 0.6662F) * 1.4F
				* p_78087_2_;
	}

}
