// Date: 3/13/2016 4:43:04 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ToxicMobModel extends ModelBase {
	// fields
	ModelRenderer Legl;
	ModelRenderer Legr;
	ModelRenderer Body;
	ModelRenderer Arml;
	ModelRenderer Armr;
	ModelRenderer Head;

	public ToxicMobModel() {
		textureWidth = 64;
		textureHeight = 32;

		Legl = new ModelRenderer(this, 0, 0);
		Legl.addBox(0F, 0F, 0F, 2, 6, 2);
		Legl.setRotationPoint(-4F, 18F, 0F);
		Legl.setTextureSize(64, 32);
		Legl.mirror = true;
		setRotation(Legl, 0F, 0F, 0F);
		Legr = new ModelRenderer(this, 0, 10);
		Legr.addBox(0F, 0F, 0F, 2, 6, 2);
		Legr.setRotationPoint(0F, 18F, 0F);
		Legr.setTextureSize(64, 32);
		Legr.mirror = true;
		setRotation(Legr, 0F, 0F, 0F);
		Body = new ModelRenderer(this, 0, 22);
		Body.addBox(0F, 0F, -3F, 8, 6, 4);
		Body.setRotationPoint(-5F, 12F, 2F);
		Body.setTextureSize(64, 32);
		Body.mirror = true;
		setRotation(Body, 0F, 0F, 0F);
		Arml = new ModelRenderer(this, 23, 0);
		Arml.addBox(0F, 0F, -1F, 1, 6, 1);
		Arml.setRotationPoint(3F, 14F, 1F);
		Arml.setTextureSize(64, 32);
		Arml.mirror = true;
		setRotation(Arml, 0F, 0F, 0F);
		Armr = new ModelRenderer(this, 30, 0);
		Armr.addBox(0F, 0F, 0F, 1, 6, 1);
		Armr.setRotationPoint(-6F, 14F, 0F);
		Armr.setTextureSize(64, 32);
		Armr.mirror = true;
		setRotation(Armr, 0F, 0F, 0F);
		Head = new ModelRenderer(this, 38, 10);
		Head.addBox(0F, 0F, 0F, 4, 3, 2);
		Head.setRotationPoint(-3F, 9F, 0F);
		Head.setTextureSize(64, 32);
		Head.mirror = true;
		setRotation(Head, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3,
			float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		Legl.render(f5);
		Legr.render(f5);
		Body.render(f5);
		Arml.render(f5);
		Armr.render(f5);
		Head.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3,
			float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);

		this.Head.rotateAngleY = f3 / (180F / (float) Math.PI);
		this.Head.rotateAngleX = f4 / (180F / (float) Math.PI);
		this.Armr.rotateAngleX = MathHelper.cos(f * 0.6662F + (float) Math.PI)
				* 2.0F * f1 * 0.5F;
		this.Arml.rotateAngleX = MathHelper.cos(f * 0.6662F) * 2.0F * f1 * 0.5F;
		this.Armr.rotateAngleZ = 0.0F;
		this.Arml.rotateAngleZ = 0.0F;
		this.Legr.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
		this.Legl.rotateAngleX = MathHelper.cos(f * 0.6662F + (float) Math.PI)
				* 1.4F * f1;
		this.Legr.rotateAngleY = 0.0F;
		this.Legl.rotateAngleY = 0.0F;

	}

}
